services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: chatbot
    volumes:
      - chatbot-pg-data:/var/lib/postgresql
    mem_limit: 256m
    cpus: 0.5

  web:
    build:
      context: .
      target: runner
    env_file: .env
    environment:
      DB_HOST: db
      DB_NAME: chatbot
      DB_USER: myuser
      DB_PASSWORD: "1234"
    expose:
      - "8000"
    depends_on:
      - db
    mem_limit: 256m
    cpus: 1.0

  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  chatbot-pg-data:
